import express from "express";
import upload from "../config/multerConfig.js";
import multer from "multer";
const router = express.Router();

import FATSDBODBC from "../controllers/controllersODBC.js";

import FATSDB from "../controllers/controlletrsMSSQL.js";
import {
  checkAuthentication,
  checkRole,
  generateToken,
} from "../helpers/apiAuth.js";
import logoUpload from "../config/multerLogoConfig.js";

const storage = multer.diskStorage({
  destination: "../uploads",
  filename: function (req, file, cb) {
    return cb(
      null,
      `${file.fieldname}_${Date.now()}${path.extname(file.originalname)}`
    );
  },
});
var uploadee = multer({
  storage: storage,
  limits: { fileSize: 1000000000000000000000 },
});
router.use("/profile", express.static("uploads"));
const cpUpload = upload.fields([
  { name: "Image" },
  { name: "Photo" },
  { name: "ItemPhoto" },
  { name: "PDFFileName" },
  {name:"ProductPhoto"}
]);
//----------------POST_API---------------------------------------------------------
router.post("/apt_post", cpUpload, FATSDB.apt_post)
router.post("/aptbckgrd_post", FATSDB.aptbckgrd_post)
router.post("/contact_post", cpUpload, FATSDB.contact_post)
router.post("/TransactionSummary_post", FATSDB.TransactionSummary_post)
router.post("/TransactionSummaryList_post", FATSDB.TransactionSummaryList_post)
router.post("/TransactionSummaryPrint_post", FATSDB.TransactionSummaryPrint_post)
router.post("/TransactionSummarytmp_post", FATSDB.TransactionSummarytmp_post)
router.post("/CardTypes_post", FATSDB.CardTypes_post)
router.post("/Companies_post", FATSDB.Companies_post)
router.post("/Customers_post", FATSDB.Customers_post)
router.post("/FEMembers_post", FATSDB.FEMembers_post)
router.post("/ItemBarcodes_post", FATSDB.ItemBarcodes_post)
router.post("/ItemBarcodesOnVan_post", FATSDB.ItemBarcodesOnVan_post)
router.post("/ItemBarcodesReturns_post", FATSDB.ItemBarcodesReturns_post)
router.post("/ItemBarcodesTmp_post", FATSDB.ItemBarcodesTmp_post)
router.post("/ItemMaster_post", cpUpload, FATSDB.ItemMaster_post)
router.post("/LIMembers_post", FATSDB.LIMembers_post)
router.post("/MemberProducts_post", FATSDB.MemberProducts_post)
router.post("/Members_post", FATSDB.Members_post)
router.post("/PDFs_post", cpUpload, FATSDB.PDFs_post)
router.post("/PDFsRPrintInvoice_post", cpUpload, FATSDB.PDFsRPrintInvoice_post)
router.post("/tblPDFsRPrintInvoiceDirect_post", cpUpload, FATSDB.tblPDFsRPrintInvoiceDirect_post)
router.post("/PDFsSalesCollectionPrint_post", cpUpload, FATSDB.PDFsSalesCollectionPrint_post)
router.post("/PDFsSalesCollectionReprint_post", cpUpload, FATSDB.PDFsSalesCollectionReprint_post)
router.post("/PDFsSalesReturnPrint_post", cpUpload, FATSDB.PDFsSalesReturnPrint_post)
router.post("/PDFsSalesReturnReprint_post", cpUpload, FATSDB.PDFsSalesReturnReprint_post)
router.post("/PDFsSummary_post", FATSDB.PDFsSummary_post)
router.post("/QRCodeLogin_post", FATSDB.QRCodeLogin_post)
router.post("/RequestDets_post", cpUpload, FATSDB.RequestDets_post)
router.post("/RequestDetsSHP_post", cpUpload, FATSDB.RequestDetsSHP_post)
router.post("/RequestMaster_post", FATSDB.RequestMaster_post)
router.post("/RequestMasterSHP_post", FATSDB.RequestMasterSHP_post)
router.post("/RouteDetails_post", FATSDB.RouteDetails_post)
router.post("/RouteMasterData_post", FATSDB.RouteMasterData_post)
router.post("/RouteMasterPlan_post", FATSDB.RouteMasterPlan_post)
router.post("/RouteMasterPlan1_post", FATSDB.RouteMasterPlan1_post)
router.post("/RouteMasterPlanDownloaded_post", FATSDB.RouteMasterPlanDownloaded_post)
router.post("/SalesCustomers_post", FATSDB.SalesCustomers_post)
router.post("/SalesCustomersReturn_post", FATSDB.SalesCustomersReturn_post)
router.post("/SalesInvoiceDets_post", FATSDB.SalesInvoiceDets_post)
router.post("/SalesInvoiceM_post", FATSDB.SalesInvoiceM_post)
router.post("/SalesInvoiceMList_post",FATSDB.SalesInvoiceMList_post)
//--------------------------------------------------------------------------

//-------------------------------GET_API---------------------------------------------
router.get("/apt_GET_LIST", FATSDB.apt_GET_LIST)
router.get("/apt_GET_BYID/:APTID", FATSDB.apt_GET_BYID)
router.get("/aptbckgrd_GET_LIST", FATSDB.aptbckgrd_GET_LIST)
router.get("/aptbckgrd_GET_BYID/:APTBckgrdID", FATSDB.aptbckgrd_GET_BYID)
router.get("/contact_GET_BYID/:ContactID", FATSDB.contact_GET_BYID)
router.get("/contact_GET_LIST", FATSDB.contact_GET_LIST)
router.get("/TransactionSummary_GET_LIST", FATSDB.TransactionSummary_GET_LIST)
router.get("/TransactionSummary_GET_BYID/:TblSysNoCounterID", FATSDB.TransactionSummary_GET_BYID)
router.get("/TransactionSummaryList_GET_LIST", FATSDB.TransactionSummaryList_GET_LIST)
router.get("/TransactionSummaryList_GET_BYID/:TblSysNoCounterID", FATSDB.TransactionSummaryList_GET_BYID)
router.get("/TransactionSummaryPrint_GET_BYID/:TblSysNoCounterID", FATSDB.TransactionSummaryPrint_GET_BYID)
router.get("/TransactionSummaryPrint_GET_LIST", FATSDB.TransactionSummaryPrint_GET_LIST)
router.get("/TransactionSummarytmp_GET_LIST", FATSDB.TransactionSummarytmp_GET_LIST)
router.get("/TransactionSummarytmp_GET_BYID/:TblSysNoCounterID", FATSDB.TransactionSummarytmp_GET_BYID)
router.get("/CardTypes_GET_BYID/:tblItemBarcodesID", FATSDB.CardTypes_GET_BYID)
router.get("/CardTypes_GET_LIST", FATSDB.CardTypes_GET_LIST)
router.get("/Companies_GET_LIST", FATSDB.Companies_GET_LIST)
router.get("/Companies_GET_BYID/:tblCompaniesID", FATSDB.Companies_GET_BYID)
router.get("/Customers_GET_BYID/:TblCustomersID", FATSDB.Customers_GET_BYID)
router.get("/Customers_GET_LIST", FATSDB.Customers_GET_LIST)
router.get("/FEMembers_GET_LIST", FATSDB.FEMembers_GET_LIST)
router.get("/FEMembers_GET_BYID/:tblLIMembersID", FATSDB.FEMembers_GET_BYID)
router.get("/temBarcodes_GET_BYID/:tblItemBarcodesID", FATSDB.temBarcodes_GET_BYID)
router.get("/ItemBarcodes_GET_LIST", FATSDB.ItemBarcodes_GET_LIST)
router.get("/ItemBarcodesOnVan_GET_LIST", FATSDB.ItemBarcodesOnVan_GET_LIST)
router.get("/ItemBarcodesOnVan_GET_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesOnVan_GET_BYID)
router.get("/ItemBarcodesReturns_GET_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesReturns_GET_BYID)
router.get("/ItemBarcodesReturns_GET_LIST", FATSDB.ItemBarcodesReturns_GET_LIST)
router.get("/ItemBarcodesTmp_GET_LIST", FATSDB.ItemBarcodesTmp_GET_LIST)
router.get("/ItemBarcodesTmp_GET_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesTmp_GET_BYID)
router.get("/ItemMaster_GET_BYID/:tblItemMasterID", FATSDB.ItemMaster_GET_BYID)
router.get("/ItemMaster_GET_LIST", FATSDB.ItemMaster_GET_LIST)
router.get("/LIMembers_GET_BYID/:tblLIMembersID", FATSDB.LIMembers_GET_BYID)
router.get("/LIMembers_GET_LIST", FATSDB.LIMembers_GET_LIST)
router.get("/MemberProducts_GET_LIST", FATSDB.MemberProducts_GET_LIST)
router.get("/MemberProducts_GET_BYID/:ProductID", FATSDB.MemberProducts_GET_BYID)
router.get("/Members_GET_BYID/:MemberID", FATSDB.Members_GET_BYID)
router.get("/Members_GET_LIST", FATSDB.Members_GET_LIST)
router.get("/PDFs_GET_LIST", FATSDB.PDFs_GET_LIST)
router.get("/PDFs_GET_BYID/:tblPDFsID", FATSDB.PDFs_GET_BYID)
router.get("/PDFsRPrintInvoice_GET_BYID/:tblPDFsID", FATSDB.PDFsRPrintInvoice_GET_BYID)
router.get("/PDFsRPrintInvoice_GET_LIST", FATSDB.PDFsRPrintInvoice_GET_LIST)
router.get("/PDFsRPrintInvoiceDirect_GET_LIST", FATSDB.PDFsRPrintInvoiceDirect_GET_LIST)
router.get("/PDFsRPrintInvoiceDirect_GET_BYID/:tblPDFsID", FATSDB.PDFsRPrintInvoiceDirect_GET_BYID)
router.get("/PDFsSalesCollectionPrint_GET_BYID/:tblPDFsID", FATSDB.PDFsSalesCollectionPrint_GET_BYID)
router.get("/PDFsSalesCollectionPrint_GET_LIST", FATSDB.PDFsSalesCollectionPrint_GET_LIST)
router.get("/PDFsSalesCollectionReprint_GET_LIST", FATSDB.PDFsSalesCollectionReprint_GET_LIST)
router.get("/PDFsSalesCollectionReprint_GET_BYID/:tblPDFsID", FATSDB.PDFsSalesCollectionReprint_GET_BYID)
router.get("/PDFsSalesReturnPrint_GET_LIST", FATSDB.PDFsSalesReturnPrint_GET_LIST)
router.get("/PDFsSalesReturnPrint_GET_BYID/:tblPDFsID", FATSDB.PDFsSalesReturnPrint_GET_BYID)
router.get("/PDFsSalesReturnReprint_GET_BYID/:tblPDFsID", FATSDB.PDFsSalesReturnReprint_GET_BYID)
router.get("/PDFsSalesReturnReprint_GET_LIST", FATSDB.PDFsSalesReturnReprint_GET_LIST)
router.get("/PDFsSummary_GET_LIST", FATSDB.PDFsSummary_GET_LIST)
router.get("/PDFsSummary_GET_BYID/:tblPDFsID", FATSDB.PDFsSummary_GET_BYID)
router.get("/QRCodeLogin_GET_BYID/:tblQRCodeLoginID", FATSDB.QRCodeLogin_GET_BYID)
router.get("/QRCodeLogin_GET_LIST", FATSDB.QRCodeLogin_GET_LIST)
router.get("/RequestDets_GET_LIST", FATSDB.RequestDets_GET_LIST)
router.get("/RequestDets_GET_BYID/:tblRequestMasterID", FATSDB.RequestDets_GET_BYID)
router.get("/RequestDetsSHP_GET_BYID/:tblRequestMasterID", FATSDB.RequestDetsSHP_GET_BYID)
router.get("/RequestDetsSHP_GET_LIST", FATSDB.RequestDetsSHP_GET_LIST)
router.get("/RequestMaster_GET_LIST", FATSDB.RequestMaster_GET_LIST)
router.get("/RequestMaster_GET_BYID/:tblRequestMasterID", FATSDB.RequestMaster_GET_BYID)
router.get("/RequestMasterSHP_GET_BYID/:tblRequestMasterID", FATSDB.RequestMasterSHP_GET_BYID)
router.get("/RequestMasterSHP_GET_LIST", FATSDB.RequestMasterSHP_GET_LIST)
router.get("/RouteDetails_GET_LIST", FATSDB.RouteDetails_GET_LIST)
router.get("/RouteDetails_GET_BYID/:tblRouteMasterID", FATSDB.RouteDetails_GET_BYID)
router.get("/RouteMasterData_GET_BYID/:tblRouteMasterDataID", FATSDB.RouteMasterData_GET_BYID)
router.get("/RouteMasterData_GET_LIST", FATSDB.RouteMasterData_GET_LIST)
router.get("/RouteMasterPlan_GET_LIST", FATSDB.RouteMasterPlan_GET_LIST)
router.get("/RouteMasterPlan_GET_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlan_GET_BYID)
router.get("/RouteMasterPlan1_GET_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlan1_GET_BYID)
router.get("/RouteMasterPlan1_GET_LIST", FATSDB.RouteMasterPlan1_GET_LIST)
router.get("/RouteMasterPlanDownloaded_GET_LIST", FATSDB.RouteMasterPlanDownloaded_GET_LIST)
router.get("/RouteMasterPlanDownloaded_GET_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlanDownloaded_GET_BYID)
router.get("/SalesCustomers_GET_BYID/:tblSalesCustomersID", FATSDB.SalesCustomers_GET_BYID)
router.get("/SalesCustomers_GET_LIST", FATSDB.SalesCustomers_GET_LIST)
router.get("/SalesCustomersReturn_GET_LIST", FATSDB.SalesCustomersReturn_GET_LIST)
router.get("/SalesCustomersReturn_GET_BYID/:tblSalesCustomersID", FATSDB.SalesCustomersReturn_GET_BYID)
router.get("/SalesInvoiceDets_GET_BYID/:tblSalesInvoiceMID", FATSDB.SalesInvoiceDets_GET_BYID)
router.get("/SalesInvoiceDets_GET_LIST", FATSDB.SalesInvoiceDets_GET_LIST)
router.get("/SalesInvoiceM_GET_LIST", FATSDB.SalesInvoiceM_GET_LIST)
router.get("/SalesInvoiceM_GET_BYID/:tblSalesInvoiceMID", FATSDB.SalesInvoiceM_GET_BYID)
router.get("/SalesInvoiceMList_GET_BYID/:tblSalesInvoiceMListID", FATSDB.SalesInvoiceMList_GET_BYID)
router.get("/SalesInvoiceMList_GET_LIST", FATSDB.SalesInvoiceMList_GET_LIST)
//------------------------------------------------------------------------------
//-----------------------------------PUT_API-------------------------------------
router.put("/apt_Put/:APTID", cpUpload, FATSDB.apt_Put)
router.put("/aptbckgrd_Put/:APTBckgrdID", FATSDB.aptbckgrd_Put)
router.put("/contact_Put/:ContactID", cpUpload, FATSDB.contact_Put)
router.put("/TransactionSummary_Put/:TblSysNoCounterID", FATSDB.TransactionSummary_Put)
router.put("/TransactionSummaryList_Put/:TblSysNoCounterID", FATSDB.TransactionSummaryList_Put)
router.put("/TransactionSummaryPrint_Put/:TblSysNoCounterID", FATSDB.TransactionSummaryPrint_Put)
router.put("/TransactionSummarytmp_Put/:TblSysNoCounterID", FATSDB.TransactionSummarytmp_Put)
router.put("/CardTypes_Put/:tblItemBarcodesID", FATSDB.CardTypes_Put)
router.put("/Companies_Put/:tblCompaniesID", FATSDB.Companies_Put)
router.put("/Customers_Put/:TblCustomersID", FATSDB.Customers_Put)
router.put("/FEMembers_Put/:tblLIMembersID", FATSDB.FEMembers_Put)
router.put("/ItemBarcodes_Put/:tblItemBarcodesID", FATSDB.ItemBarcodes_Put)
router.put("/ItemBarcodesOnVan_Put/:tblItemBarcodesID", FATSDB.ItemBarcodesOnVan_Put)
router.put("/ItemBarcodesReturns_Put/:tblItemBarcodesID", FATSDB.ItemBarcodesReturns_Put)
router.put("/ItemBarcodesTmp_Put/:tblItemBarcodesID", FATSDB.ItemBarcodesTmp_Put)
router.put("/ItemMaster_Put/:tblItemMasterID", cpUpload, FATSDB.ItemMaster_Put)
router.put("/LIMembers_Put/:tblLIMembersID", FATSDB.LIMembers_Put)
router.put("/MemberProducts_Put/:ProductID", FATSDB.MemberProducts_Put)
router.put("/Members_Put/:MemberID", FATSDB.Members_Put)
router.put("/PDFs_Put/:tblPDFsID", cpUpload, FATSDB.PDFs_Put)
router.put("/PDFsRPrintInvoice_Put/:tblPDFsID", cpUpload, FATSDB.PDFsRPrintInvoice_Put)
router.put("/PDFsRPrintInvoiceDirect_Put/:tblPDFsID", cpUpload, FATSDB.PDFsRPrintInvoiceDirect_Put)
router.put("/PDFsSalesCollectionPrint_Put/:tblPDFsID", cpUpload, FATSDB.PDFsSalesCollectionPrint_Put)
router.put("/PDFsSalesCollectionReprint_Put/:tblPDFsID", cpUpload, FATSDB.PDFsSalesCollectionReprint_Put)
router.put("/PDFsSalesReturnPrint_Put/:tblPDFsID", cpUpload, FATSDB.PDFsSalesReturnPrint_Put)
router.put("/PDFsSalesReturnReprint_Put/:tblPDFsID", cpUpload, FATSDB.PDFsSalesReturnReprint_Put)
router.put("/PDFsSummary_Put/:tblPDFsID", FATSDB.PDFsSummary_Put)
router.put("/QRCodeLogin_Put/:tblQRCodeLoginID", FATSDB.QRCodeLogin_Put)
router.put("/RequestDets_Put/:tblRequestMasterID", cpUpload, FATSDB.RequestDets_Put)
router.put("/RequestDetsSHP_Put/:tblRequestMasterID", cpUpload, FATSDB.RequestDetsSHP_Put)
router.put("/RequestMaster_Put/:tblRequestMasterID", FATSDB.RequestMaster_Put)
router.put("/RequestMasterSHP_Put/:tblRequestMasterID", FATSDB.RequestMasterSHP_Put)
router.put("/RouteDetails_Put/:tblRouteMasterID", FATSDB.RouteDetails_Put)
router.put("/RouteMasterData_Put/:tblRouteMasterDataID", FATSDB.RouteMasterData_Put)
router.put("/RouteMasterPlan_Put/:tblRouteMasterID", FATSDB.RouteMasterPlan_Put)
router.put("/RouteMasterPlan1_Put/:tblRouteMasterID",FATSDB.RouteMasterPlan1_Put)
router.put("/RouteMasterPlanDownloaded_Put/:tblRouteMasterID", FATSDB.RouteMasterPlanDownloaded_Put)
router.put("/SalesCustomers_Put/:tblSalesCustomersID", FATSDB.SalesCustomers_Put)
router.put("/SalesCustomersReturn_Put/:tblSalesCustomersID", FATSDB.SalesCustomersReturn_Put)
router.put("/SalesInvoiceDets_Put/:tblSalesInvoiceMID", FATSDB.SalesInvoiceDets_Put)
router.put("/SalesInvoiceM_Put/:tblSalesInvoiceMID", FATSDB.SalesInvoiceM_Put)
router.put("/SalesInvoiceMList_Put/:tblSalesInvoiceMListID" , FATSDB.SalesInvoiceMList_Put)
//---------------------------------------------------------------------------------------------------------------

//-----------------------------------DELETE_API------------------------------------------------------------------
router.delete("/apt_DELETE_BYID/:APTID", FATSDB.apt_DELETE_BYID)
router.delete("/aptbckgrd_DELETE_BYID/:APTBckgrdID", FATSDB.aptbckgrd_DELETE_BYID)
router.delete("/contact_DELETE_BYID/:ContactID", FATSDB.contact_DELETE_BYID)
router.delete("/TransactionSummary_DELETE_BYID/:TblSysNoCounterID", FATSDB.TransactionSummary_DELETE_BYID)
router.delete("/TransactionSummaryList_DELETE_BYID/:TblSysNoCounterID", FATSDB.TransactionSummaryList_DELETE_BYID)
router.delete("/TransactionSummaryPrint_DELETE_BYID/:TblSysNoCounterID", FATSDB.TransactionSummaryPrint_DELETE_BYID)
router.delete("/TransactionSummarytmp_DELETE_BYID/:TblSysNoCounterID", FATSDB.TransactionSummarytmp_DELETE_BYID)
router.delete("/CardTypes_DELETE_BYID/:tblItemBarcodesID", FATSDB.CardTypes_DELETE_BYID)
router.delete("/Companies_DELETE_BYID/:tblCompaniesID", FATSDB.Companies_DELETE_BYID)
router.delete("/Customers_DELETE_BYID/:TblCustomersID", FATSDB.Customers_DELETE_BYID)
router.delete("/FEMembers_DELETE_BYID/:tblLIMembersID", FATSDB.FEMembers_DELETE_BYID)
router.delete("/ItemBarcodes_DELETE_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodes_DELETE_BYID)
router.delete("/ItemBarcodesOnVan_DELETE_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesOnVan_DELETE_BYID)
router.delete("/ItemBarcodesReturns_DELETE_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesReturns_DELETE_BYID)
router.delete("/ItemBarcodesTmp_DELETE_BYID/:tblItemBarcodesID", FATSDB.ItemBarcodesTmp_DELETE_BYID)
router.delete("/ItemMaster_DELETE_BYID/:tblItemMasterID", FATSDB.ItemMaster_DELETE_BYID)
router.delete("/LIMembers_DELETE_BYID/:tblLIMembersID", FATSDB.LIMembers_DELETE_BYID)
router.delete("/MemberProducts_DELETE_BYID/:ProductID", FATSDB.MemberProducts_DELETE_BYID)
router.delete("/Members_DELETE_BYID/:MemberID", FATSDB.Members_DELETE_BYID)
router.delete("/PDFs_DELETE_BYID/:tblPDFsID", FATSDB.PDFs_DELETE_BYID)
router.delete("/PDFsRPrintInvoice_DELETE_BYID/:tblPDFsID", FATSDB.PDFsRPrintInvoice_DELETE_BYID)
router.delete("/PDFsRPrintInvoiceDirect_DELETE_BYID/:tblPDFsID", FATSDB.PDFsRPrintInvoiceDirect_DELETE_BYID)
router.delete("/PDFsSalesCollectionPrint_DELETE_BYID/:tblPDFsID", FATSDB.PDFsSalesCollectionPrint_DELETE_BYID)
router.delete("/PDFsSalesCollectionReprint_DELETE_BYID/:tblPDFsID", FATSDB.PDFsSalesCollectionReprint_DELETE_BYID)
router.delete("/PDFsSalesReturnPrint_DELETE_BYID/:tblPDFsID", FATSDB.PDFsSalesReturnPrint_DELETE_BYID)
router.delete("/PDFsSalesReturnReprint_DELETE_BYID/:tblPDFsID", FATSDB.PDFsSalesReturnReprint_DELETE_BYID)
router.delete("/PDFsSummary_DELETE_BYID/:tblPDFsID", FATSDB.PDFsSummary_DELETE_BYID)
router.delete("/QRCodeLogin_DELETE_BYID/:tblQRCodeLoginID", FATSDB.QRCodeLogin_DELETE_BYID)
router.delete("/RequestDets_DELETE_BYID/:tblRequestMasterID", FATSDB.RequestDets_DELETE_BYID)
router.delete("/RequestDetsSHP_DELETE_BYID/:tblRequestMasterID", FATSDB.RequestDetsSHP_DELETE_BYID)
router.delete("/RequestMaster_DELETE_BYID/:tblRequestMasterID", FATSDB.RequestMaster_DELETE_BYID)
router.delete("/RequestMasterSHP_DELETE_BYID/:tblRequestMasterID", FATSDB.RequestMasterSHP_DELETE_BYID)
router.delete("/RouteDetails_DELETE_BYID/:tblRouteMasterID", FATSDB.RouteDetails_DELETE_BYID)
router.delete("/RouteMasterData_DELETE_BYID/:tblRouteMasterDataID", FATSDB.RouteMasterData_DELETE_BYID)
router.delete("/RouteMasterPlan_DELETE_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlan_DELETE_BYID)
router.delete("/RouteMasterPlan1_DELETE_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlan1_DELETE_BYID)
router.delete("/RouteMasterPlanDownloaded_DELETE_BYID/:tblRouteMasterID", FATSDB.RouteMasterPlanDownloaded_DELETE_BYID)
router.delete("/SalesCustomers_DELETE_BYID/:tblSalesCustomersID", FATSDB.SalesCustomers_DELETE_BYID)
router.delete("/SalesCustomersReturn_DELETE_BYID/:tblSalesCustomersID", FATSDB.SalesCustomersReturn_DELETE_BYID)
router.delete("/SalesInvoiceDets_DELETE_BYID/:tblSalesInvoiceMID", FATSDB.SalesInvoiceDets_DELETE_BYID)
router.delete("/SalesInvoiceM_DELETE_BYID/:tblSalesInvoiceMID", FATSDB.SalesInvoiceM_DELETE_BYID)
router.delete("/SalesInvoiceMList_DELETE_BYID/:tblSalesInvoiceMListID", FATSDB.SalesInvoiceMList_DELETE_BYID)
//----------------------------------------------------------------------------////
export default router;
